### ISSUE TITLE
xmlutil-serialization 0.11.1.1 is missing js artifact

### ISSUE THREAD

**Issue by altavir** [pdvrieze/xmlutil#10]
The reference is present in the module file, but the artifact itself is missing.

**Comment by altavir** [comment]
I've also noted that you are probably using old gradle, since metadata version is 0.4. I think it is a good idea to upgrade gradle to the one coming with 1.0  to provide better compatibility.

**Comment by pdvrieze** [comment]
I've added the js artifact to bintray. I've since updated the gradle version to a newer one, but I'll wait until the next release to do use it properly (old gradle versions complain about the new version - I tested it in maven local). Please reopen if the old metadata version is a problem.

I didn't add the target specific module files as there are to many ways that can go wrong (they have checksums and I updated gradle locally and pushed that to maven local).

**Comment by pdvrieze** [comment]
Should be resolved now.
