### ISSUE TITLE
Support for polymorphic deserializers base on tag name

### ISSUE THREAD

**Issue by altavir** [pdvrieze/xmlutil#11]
Suppose we have a sealed class hierarchy like this:
```kotlin
sealed class S

@SerialName("a")
class A: Parent()

@SerialName("b")
class b: Parent()

class Holder{
  val children = ArrayList<@ContextualSerialization S>()
}
```
Then we create an array of `S` and pass it to serializer via `ContextSerializer, obtaining something like
```xml
<Holder>
  <a>...</a>
  <b>...</b>
</Holder>
```
Currently deserializer tries to interpret those tags as fields. It is important to be able to somehow tell it that those are parts of the list.

**Comment by pdvrieze** [comment]
Ok. currently (and based upon old versions of the serialization library sealed class serialization is the same as regular polymorphic serialization. The challenge is exactly to know which the possible child types are and what their corresponding tag names would be. It will have a look whether using ContextualSerialization may help, but even there the problem is how we support eliding the standard polymorphic container (that the serialization library wants to use - and I want to allow you to avoid)

Unfortunately it is not possible with the current serialization library without additional annotations. For now, a sealed class works exactly the same as a regular polymorphic list.

**Comment by altavir** [comment]
As far as I can understand, currently, polymorphic serialize requires a serialization module which contains a map class->serializer for each of polymorphic types. Since we have a tag name for each class, it seems to be quite easy to search those serial names in addition to field names when we encounter the tag. I've scanned through sources and even localized possible place where the feature should be added (I can find it again later), but decided not to do anything for now since the code is rather sophisticated..

We try to use `xmlutil` in one large project right now and this problem is a real show-stopper since XML schema is fixed. I've separated XML part in a separate project here: https://github.com/mipt-npm/gdml.kt. The idea is to make [this one](https://github.com/mipt-npm/gdml.kt/blob/aba6da8943af6c2394ef986b9cf21bfee49c81f9/src/commonTest/kotlin/scientifik/gdml/GDMLTest.kt#L28) work.

**Comment by pdvrieze** [comment]
I'll have a look, but I'm about to have a 10+ hour flight home. I just checked. SerialModule does have the `dumpTo` function that should be able to be used to find appropriate (de)serializers. I could use that as a fallback before the code triggers "unknown field".

In the meantime the `@XmlPolyChildren` annotation should be able to do this by hand. It does smart class name lookup (in the same package as the owner class).

**Comment by pdvrieze** [comment]
Thinking about it, it should be possible to support sealed children as long as the module is provided. Even without using the contextual annotation. Of course sealed classes will be properly supported by kotlinx.serialization in the future.

**Comment by altavir** [comment]
I tried to use `@XmlPolyChildren`, but I did not understand, how it works. 
Also I've noticed that applying PolymorphicSerializer (with proper module) produces not the same result as ContextualSerializer. I think the result should be the same.

**Comment by pdvrieze** [comment]
`@XmlPolyChildren` basically allows you to specify all valid subtypes that will be recognized. The straightforward version takes the FQN of the type, but if you don't include a package name it will use the package of the containing type. You are also able to rename the value by specifying the "=newName" after the type name.

I've started work on a mode that does automatic polymorhpism based upon serialmodules. It still needs the `@Polymorphic` annotation though as that annotation triggers polymorphic processing. Good news is that (with some hackery due to a private property in the library) it works. For now I'll only enable it conditionally, as it breaks various tests (basically it no longer uses the wrappers that specify the type and content, but instead the result is the same as if you used XmlPolyChildren). The new behaviour is more elegant, but breaks existing formats.

The reason that ContextualSerializer doesn't work is that:

- `PolymorphicSerializer` is actually also a form of contextual serialization
- `ContextualSerializer` allows you to look up the serializer for a specific type at runtime rather than at compile time. ContextualSerializer will just directly delegate to that serializer.
- To support polymorphism (for reading) you need to have a way to determine which serializer to use based upon the data you parse. By default PolymorphicSerializer does this by creating a synthetic structure that has two members: type and value. In XML it is possible to use the tag name instead to distinguish types (but you need a mapping from tag name to type - hence the need to enumerate all possible serializers/classes)

**Comment by altavir** [comment]
I managed to make serialization and deserialization working by writing:
```kotlin
    @XmlPolyChildren(["position","rotation"])
    val content = ArrayList<@Polymorphic GDMLDefine>()
```
Class names work for serialization, but do not work for deserialization since they are not resolved to serial names.

**Comment by pdvrieze** [comment]
They should work for deserialization. In any case, the new approach that uses the serialmodule should be able to support it. Any test case that breaks stuff is always welcome.

**Comment by altavir** [comment]
I've tried master build. It works for serialization, but does not seem to work for deserialization.

The problematic piece looks like this:
```kotlin
    //@XmlPolyChildren(arrayOf("constant", "quantity", "variable", "position", "rotation", "scale", "matrix"))
    val content = ArrayList<@Polymorphic GDMLDefine>()
```

The module is properly defined:
```kotlin
val gdmlModule = SerializersModule {
    polymorphic<GDMLDefine> {
        GDMLRotation::class with GDMLRotation.serializer()
        GDMLPosition::class with GDMLPosition.serializer()
        GDMLConstant::class with GDMLConstant.serializer()
        GDMLVariable::class with GDMLVariable.serializer()
        GDMLQuantity::class with GDMLQuantity.serializer()
        GDMLScale::class with GDMLScale.serializer()
    }
    ...
}

        val format = XML(gdmlModule) {
            autoPolymorphic = true
            indent = 4
            unknownChildHandler = WARNING_UNKNOWN_CHILD_HANDLER
        }
```
And I get the error:
```
scientifik.gdml.GDMLRotation is not registered for polymorphic serialization in the scope of class scientifik.gdml.GDMLDefine
```

Maybe I am missing some annotations?

**Comment by pdvrieze** [comment]
I've just pushed some changes in this area that may fix this (I didn't see your bug, but Javascript didn't work correctly). Javascript deserialization was broken (as well as serialization somewhat). Basically the PolymorphicSerializer no longer writes the class name, but the name in the serialdescriptor (which by default is set at compile time to the class name, but is affected by the `@SerialName` annotation -- the property names in the code still refer to it as `klassName`). Unfortunately the JavaScript class name does not contain the package. I suspect you use `@SerialName` so the code would be broken without the fix.

This error is one that comes from the kotlinx.serialization library. It is normally triggered through PolymorphicSerializer. It would mean that either the module is somehow lost/not used, or that the name used to look it up is not correct.

**Comment by altavir** [comment]
I've just pushed a code with the error: https://github.com/mipt-npm/gdml.kt/blob/5ab762249e74af3115d81dc030a760b2cf9531a4/src/commonTest/kotlin/scientifik/gdml/GDMLTest.kt#L36
I will try to pull master and repeat the test.

**Comment by altavir** [comment]
Seems to be working now!

**Comment by pdvrieze** [comment]
There was actually a new bug in the @XmlPolyChildren processing. I'm about to push code that breaks that. Basically the short class name will now require a leading "." as is used in other places. (This allows distinguishing a class that needs a package name from a class name without a package - as created by `@SerialName`).

**Comment by pdvrieze** [comment]
> I managed to make serialization and deserialization working by writing:
> 
> ```kotlin
>     @XmlPolyChildren(["position","rotation"])
>     val content = ArrayList<@Polymorphic GDMLDefine>()
> ```
> 
> Class names work for serialization, but do not work for deserialization since they are not resolved to serial names.

This problem should now also be "fixed". As that it will match whatever is returned by `serializer.descriptor.name` where `serializer` is the serializer that is matched to the type.

**Comment by altavir** [comment]
Good, probably it will make sense for `@XMLPolyChildren` to accept classes, not strings, or both.

**Comment by pdvrieze** [comment]
I've added some documentation to the README. I'll keep `@XmlPolyChildren` as is for now. The main use case with the new autoPolymorphism is where it is necessary to specify the use tag name at use site (not on the type - something incompatible with normal use of XmlSchema). I'm not sure that class arrays are supported by the serialization plugin yet.
