### ISSUE TITLE
Performance regression in 0.84.3 - overzealous debug logging?

### ISSUE THREAD

**Issue by jpd236** [pdvrieze/xmlutil#119]
There is noticeably slower performance in my app, a Chrome extension which is serializing a file to XML (using Kotlin/JS), when upgrading from 0.84.2 to 0.84.3.

While I haven't traced it too finely, there is a very observable difference - in the Chrome console, there is a ton of console logging that begins, "DEBUG - attribute - ..." - like thousands of lines (one per attribute?) over what is at most a 1-2 second operation. It seems [plausible](https://stackoverflow.com/questions/11426185/will-console-log-reduce-javascript-execution-performance) that this is causing a bottleneck.

Perhaps this logging was unintentionally committed as part of https://github.com/pdvrieze/xmlutil/commit/25bd97374f281f5a17699e7a7d406b776f6c92cd and should just be removed or put behind some other `if (DEBUG)` check?

**Comment by pdvrieze** [comment]
You're right. They shouldn't have been there. Btw. for performance you may want to try using the platform independent writer rather than the default DOM based writer (Either create `KtXmlWriter` directly or use `XmlStreaming.newGenericWriter` - it does the same, but `XmlStreaming` is the platform independent entry point). DOM is known to be slow in cases, and in general it could be faster to write Xml directly to a string rather than indirectly through DOM (dependent upon the optimization applied).

There should be an automatic snapshot released soon.

**Comment by jpd236** [comment]
Thanks!

The XML files we're dealing with here are typically ~tens of KBs... I'd hope that's small enough that any performance difference between the two wouldn't be too significant in the grand scheme of things. I don't see any significant differences from some quick testing. (It also results in very slight output differences vs. the default writer, due to use of single quotes in the doctype and spaces before the end of self-closing tags, but that is probably reconcilable, and if not, I could fix my test files).

**Comment by pdvrieze** [comment]
@jpd236 For your testing you may want to look at the test code in the library. There is actually an XML comparison tool in there that tries to compare according to XML rules (rather than string comparison). It would also make your tests more robust against different browsers as there is no set formatting that must be used (like single vs double quotes).

**Comment by pdvrieze** [comment]
Now released in [0.85.0](https://github.com/pdvrieze/xmlutil/releases/tag/v0.85.0).
