### ISSUE TITLE
Make namespace optional for @XmlSerialName

### ISSUE THREAD

**Issue by altavir** [pdvrieze/xmlutil#14]
In a code like this: 
```kotlin
    @XmlSerialName("first", "", "")
    override var first: GDMLRef<GDMLSolid>,
```
regular `@SerialName` annotation does not work for some reason (it uses `GDMLRef` as tag name instead of `first`), so I have to use `@XMLSerialName`, but writing empty strings each time is annoying. I think that additional arguments could be made optional.

**Comment by altavir** [comment]
I can contribute a fix for that.

**Comment by pdvrieze** [comment]
If you want to that would be great (But use a random "default" value - the code for that may be somewhere around in the history - the default behaviour should be different from empty namespace, probably best is to take the namespace of the container). The reason that they are not optional is that (at least in the past) optional parameters were not supported properly by the serialization plugin. If that has been fixed now, I'm all for making it optional.

Btw. The reason that `@SerialName` is because its use is hidden. `@SerialName` can be used either at use site (properties) or at declaration site (classes). While it is possible to know what each "name" is, it is not possible to know that this was a custom name rather than the property name (or fully qualified class name).

The way name handling works is as follows:

1. If the property is serialized as element content, no name is used, but only one attribute per struct can be element content
2. If the property has an `@xmlSerialName` annotation, use that
3. If the type has an `@xmlSerialName` annotation, use that
4. If the value will be serialized as attribute - use the use site name (attribute name or `@SerialName` annotation)
5. If the value is serialized as tag (the else option) - use the name of the type (with some removal of package names).

**Comment by pdvrieze** [comment]
I've had a look. If you look at `serialization/src/commonMain/kotlin/nl/adaptivity/xmlutil/serialization/annotations.kt`
You will find that the code is already there, but commented out. The serialization plugin still does not support optional parameters - you must provide a value in the use site. As soon as it is supported, the default values can be uncommented.

I may need to add some tests to check the semantics though, those tests could use the default values explicitly.

**Comment by pdvrieze** [comment]
There is a partial workaround now. Given that names are now determined through the policy it is possible for an alternative annotation to be used with an alternative (extended) policy. The annotations are available to the method in the policy that determines the tag name to be used.

**Comment by pdvrieze** [comment]
Default arguments should now be supported in kotlin master/1.5.30-pre (see https://github.com/JetBrains/kotlin/commit/229085f3d13b09f87bc5421ec4e3f4272a78fabc ). When that is released I will revisit.

**Comment by pdvrieze** [comment]
This feature somewhat works. There seems to be an incremental compilation/caching issue (or something like that), but the library supports it now (when the compiler plugin cooperates).
