### ISSUE TITLE
getAttribute on native requires prepending ":" to the attribute name

### ISSUE THREAD

**Issue by luca992** [pdvrieze/xmlutil#142]
I'm trying to decode this file on native and js:
https://github.com/luca992/Kamel/blob/darwin/kamel-tests/src/commonMain/resources/MR/files/ComposeXml.xml

I got it working. But I had to do a workaround for native where I had to prepend ":" to the attribute name. Whereas on JS that was not necessary. 

My workaround for accessing attribute values:
https://github.com/alialbaali/Kamel/pull/23/commits/98dba5d5159d347035c6743223330670e772055b

**Comment by pdvrieze** [comment]
I've fixed this in dev. Note that the correct workaround would be to use `getAttributeNS("", attributeName)`. The problem is that `Attribute.name` is implemented incorrectly (it doesn't handle the empty prefix case correctly). The namespace aware version of `getAttribute` does not have this issue (and should always be used when the document uses namespaces).
