### ISSUE TITLE
Question about excluding serialization of objects with all null attributes

### ISSUE THREAD

**Issue by Lawrance3** [pdvrieze/xmlutil#158]
If I have a data class named Income in my application. This class has three properties, all of which are nullable:
``` Kotlin
@Serializable
data class Income(
    @XmlElement(true) @SerialName("Test1")
    var test1: Int? = null,
    @XmlElement(true) @SerialName("Test2")
    var test2: Int? = null,
    @XmlElement(true) @SerialName("Test3")
    var test3: List<String?>? = null
)
```
When I instantiate this class without providing any attribute values (i.e., Income()), the library currently outputs `<Income/>` in the serialized XML.

In my use case, I'd prefer not to include "Income" in the output XML at all if all of its attributes are null. Is there an existing way to achieve this with the library?

**Comment by pdvrieze** [comment]
The library doesn't itself support this. It would be hard to support due to the incremental approach to the architecture of kotlinx.serialization. However, if you want this, it is possible to use a custom serializer. At least for xmlutil it should be possible to only serialize `Income` if one of its members is not null.

**Comment by pdvrieze** [comment]
There is another issue in that omitting the `<Income>` tag would imply it has a null value itself (because that is how the decoding works). Thinking about it in detail I think the best approach is to a delegate for the serialization (of the container) where you perform the logic for the serialization. This delegate can remain private/invisible to users.
