### ISSUE TITLE
Issue with `.` in tag names

### ISSUE THREAD

**Issue by fkrauthan** [pdvrieze/xmlutil#50]
I recently run into an issue where the XML I am consuming has tags like this: `DISPLAYCONTACT.FIRSTNAME`

My entity defines them like this: 
```kotlin
    @XmlElement(true)
    @SerialName("DISPLAYCONTACT.FIRSTNAME")
    val firstName: String? = null,
```

in the same entity class all XML elements that do not have a `.` work fine and getting deserialized accordingly but all the once with `.` just getting ignored/skipped.

**Comment by fkrauthan** [comment]
The strange thing is the `unknownChildHandler` is called for example for `DISPLAYCONTACT.FIRSTNAME` even though it's clearly deserialized.

**Comment by fkrauthan** [comment]
Ok for anyone that is running into the same issue a wrokaround is to use

```
@XmlSerialName("DISPLAYCONTACT.FIRSTNAME", "", "")
```

instead of

```
@SerialName("DISPLAYCONTACT.FIRSTNAME")
```

**Comment by pdvrieze** [comment]
I know what is going on. This is related to the mechanism that turns `serialName` values into tag names. For a type (rather than element) the serialName is the type name (if none is given with the annotation). Normally you don't want tag names with java packages in them (XML has namespaces for that).

This mechanism is implemented purely in the policy that you configure the format with. The default basically sees a `.` and assumes that this is a Kotlin type name and picks the final part only.

You can override this in `serialNameToQName` of the policy (you can extend `DefaultXmlSerializationPolicy` if you want). If you want (much) more control you can override `effectiveName` which is the user of that easier function (it is reasonably complex to deal with all kinds of special cases like built-in types as well as different policies for tags vs attributes).

The default implementation of `serialNameToQName` unfortunately provides no distinction between being called for the name of a type or for the name of an attribute. As names are part of the public API of serialization and a change in naming policy changes the names I can't really change the default without breaking peoples serialization. You could of course recognize specific names and special case them (positive or negative).

Unfortunately it is invisible to formats whether the `@SerialName` annotation was used. Which is the main reason that the `@XmlSerialName` annotation exists (btw. it is possible to process your own alternative annotations in `effectiveName`)

**Comment by pdvrieze** [comment]
As this is basically an edge case in a (best effort) heuristic to resolve a design limitation of the serialization framework I'm not sure what I can do, except suggesting to use the available mechanisms to either provide your own naming policy, or provide annotations where appropriate.

What I have done is to split `serialNameToQName` into two functions: `serialTypeNameToQName` and `serialUseNameToQName` which by default delegate to it. The default code calls these, so the policy can now differ based upon context without too much code being needed.

**Comment by fkrauthan** [comment]
Maybe this can be added to the documentation?
