### ISSUE TITLE
List deserialization fails if property name does not coincide with class class serial name

### ISSUE THREAD

**Issue by altavir** [pdvrieze/xmlutil#6]
Consider this code:
```kotlin
@Serializable
class Config {
    val jobList = mutableListOf<Job>()
}

@Serializable
@SerialName("job")
class Job {
}
```
The serialization works fine for single Job, but when deserialization fails, because it tries to find an element with name `jobList`, not `job`. When property name is the same as class serial name, it works fine.

**Comment by pdvrieze** [comment]
The problem here is the difference in how xml works (name depends on type) with how kotlinx.serialization works (name depends on property name). To handle this is a balancing act, partially because the serializer cannot know whether or not `@SerialName` actually was applied. The current code does this differently for attributes and elements. This is one of the reasons that the `@XmlSerialName` annotation is used. You can also use `@XmlChildName` for the child element in the list.
Most of my own use cases have the outer list elided (only the children are emitted - as you can see in some of the tests), but I will have a look at naming of children in the case of the list tags being present.

**Comment by altavir** [comment]
Currently in this case deserialization is not consistent with serialization, which does not look good. I understand that in XML we have two ways to represent a list - with or without wrapping. I found out that in jackson they have special annotation to specify wrapping of lists. Maybe here you should use the same - use property name for wrapper, class name for items and annotation to skip wrapper?

**Comment by pdvrieze** [comment]
The way you can force the outer/inner tag behaviour is by specifying the `@XmlChildrenName` annotation on the list property. I can see however that this is not always needed and I'll probably review the annotations available for this. The behaviour is somewhat document in https://github.com/pdvrieze/xmlutil/blob/44e7c2e9a9daebffd9edb7f0be798206aff048f7/serialization/src/commonMain/kotlin/nl/adaptivity/xmlutil/serialization/XMLEncoder.kt#L365

**Comment by pdvrieze** [comment]
This should be fixed to work consistently by now (encoder/decoder now share an XmlDescriptor as metadata to drive serialization/deserialization), even if it doesn't always use the desired name (but that can be overridden by policy).
