### ISSUE TITLE
Add ordering annotation

### ISSUE THREAD

**Issue by altavir** [pdvrieze/xmlutil#61]
Some strict XML schemas require child elements of a tag to be declared in a specific order. I think it would be nice to have an ordering annotation that allows children to be placed in a specific order during serialization and ignored during de-serialization. It could look like `XMLSerialOrder(2)`.

**Comment by pdvrieze** [comment]
The order of serialization is indicated by the order used by the serializer (which is as ordered in the source file). (actually whatever is generated by the serialization plugin). There is one special exception, attributes and tags are handled separately (attributes must always go before member tags - obviously).
The issue is also related to https://github.com/Kotlin/kotlinx.serialization/issues/121 that doesn't seem to have much a resolution at present. If I look at it, it seems the use case is mainly that you want to be able to have a different order in your code as in the serialized form and don't want to write the serializer by hand.

**Comment by altavir** [comment]
Sadly, it is not only the problem of the order in the source file. In the case where one serializable class inherits another, the order is defined by the inheritance, not the declaration order.

**Comment by pdvrieze** [comment]
Ah, that makes sense. It is also something that cannot be done by the runtime library itself as the order is determined by the (generated) serializer(s), not the runtime library. I may add an ordering mechanism to the policy. The annotations would then just be a matter for the policy to use (ie. you can do it differently if you want). Any idea what the best form of annotation would be? I can think of three annotation options:
 - A per-element annotation giving an index. All elements would be ordered according to this index and any non-annotated elements would come after (as a child could add elements, add after seems more sane).
 - A per-element annotation specifying an ordering constraint (before/after=<serialName>)
 - A type level annotation containing an ordered list of serialNames.

When I mean serialName I mean the property name (or the serialName if annotated at that level), so polymorphic children would still only have one reference.

**Comment by pdvrieze** [comment]
I've put some initial code into dev just now. It uses ordering constraints. It seems to work correctly (there is a simple test) although it doesn't have a good policy for elements without constraints though (that will come to the policy).

**Comment by pdvrieze** [comment]
If you want a look I've just pushed the code into the dev branch. It should support the use of `@XmlBefore` and `@XmlAfter` annotations to allow specifying (by serialName) ordering constraints. It is implemented so that only if any such annotation is present do you need to pay for ordering (I will still need to do some optimization and benchmarking of the whole library though - I'm sure that that there are ways to speed it up, including caching of descriptors across runs).
