### ISSUE TITLE
R8 failure with 0.84.2

### ISSUE THREAD

**Issue by yschimke** [pdvrieze/xmlutil#87]
No issue with 0.84.0

```
$ ./gradlew assembleRelease
...
* What went wrong:
Execution failed for task ':wear:minifyReleaseWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete, position: Lnl/adaptivity/xmlutil/core/KtXmlReader;next()Lnl/adaptivity/xmlutil/EventType;, origin: /Users/yurischimke/.gradle/caches/transforms-3/d6f1060ce2ab9d21b3155c5644c15069/transformed/jetified-xmlutil-android-0.84.2.jar:nl/adaptivity/xmlutil/core/KtXmlReader.class
```

Project is at https://github.com/yschimke/rememberwear

**Comment by pdvrieze** [comment]
I've had a look. I managed to make it work by switching the android gradle plugin in your code back to 7.1.3 (it does break with 7.2.0-rc02). As 7.3.0-alpha09 is an alpha release I suspect the bug is there (there seem to be older cases with similar error messages). The plugin complains about an issue in `KtXmlReader.next` which is a very boring 5 line function that hasn't changed since 0.84.1 (which does work as well), and the changes in `KtXmlReader.nextImpl` which does all the work and may end up inlined has only minimal changes. I'm not sure what I can do to diagnose what is going on here beyond bisecting..

**Comment by yschimke** [comment]
I'll raise a bug with android gradle plugin.  Thanks.

**Comment by yschimke** [comment]
https://issuetracker.google.com/issues/231804008

**Comment by pdvrieze** [comment]
I can confirm it is certainly a problem with r8. I managed to isolate it to a single line:
https://github.com/pdvrieze/xmlutil/blob/ff63f4534fcf639f00a659ae34945763cfd6b5bf/core/src/commonMain/kotlin/nl/adaptivity/xmlutil/core/KtXmlReader.kt#L260

Removing the line will make it work, moving it to be next to the similar line for `EndDocument` doesn't.

**Comment by p-fischer** [comment]
> https://issuetracker.google.com/issues/231804008

Unfortunately, the issue was marked as `Won't fix`.

As I'm running into the same error what workaround do you suggest?

@pdvrieze I'm aware the bug is not caused by your library but is there a way a new version of the library can workaround the R8 bug?

**Comment by p-fischer** [comment]
The best workaround for me is to prevent `EventType` from being obfuscated/optimized by adding the following line to the proguard rules:

```
-keep public enum nl.adaptivity.xmlutil.EventType {*;}
```

With this solution I have to downgrade neither XmlUtil nor AGP.

**Comment by p-fischer** [comment]
@pdvrieze I really appreciate this workaround for this bug, although it's not even in this library.
This is the relevant change: https://github.com/pdvrieze/xmlutil/commit/1ee587b4f928498d9a6c85e0bc1aa3bd3731971d#diff-56680283432179eea353e2facc9018d1d4f5fcd92d5730c24d085007760ce6b5
